spring.application.name=CryptoTrading

spring.datasource.url=jdbc:postgresql://localhost:8081/crypto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

coingecko.api.key=CG-HMXvotw1DZpcW9FjMfTk2oWM
stripe.api.key=asdfasdfs
razorpay.api.key=rzp_test_BbLwkBVuQvM5Zt
razorpay.api.secret=KFtSHEnlNO3BddjweGF6UsNl
server.port=8090